apiVersion: v1
kind: Service
metadata:
  name: gottyservice
  labels:
    app: gottygedit1
spec:
  selector:
    app: gottygedit1
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

