apiVersion: v1
kind: Service
metadata:
  name: javaservice2
  labels:
    app: gottyjava2
spec:
  selector:
    app: gottyjava2
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080