apiVersion: v1
kind: Service
metadata:
  name: k8gotty1-service
  labels:
    app: gottygedit1
spec:
  selector:
    app: gottygedit1
  type: NodePort
  ports:
  - nodePort: 30201
    protocol: TCP
    port: 8080
    targetPort: 8080

