apiVersion: apps/v1
kind: Deployment
metadata:
  name: gottygedit
  labels:
    app: gottygedit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gottygedit
  template:
    metadata:
      labels:
        app: gottygedit
    spec:
      hostNetwork: true
      containers:
      - name: gottygedit-conatiner
        image: cmdgottygedit
        imagePullPolicy: IfNotPresent
        resources: #not there
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: "128Mi"
            cpu: "500m" #------
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: mongo-storage
          mountPath: /data
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
  
        
      
      
