kind: Service
apiVersion: v1
metadata:
  name:  gottyservice-nodeport
  namespace: namespace-3
spec:
  selector:
    app:  nested-ctr-deploy
  type:  NodePort
  ports:
  - name:  name-of-the-port
    port:  5011
    targetPort: 5011
    # nodePort: 31515