# NOTE: The service account `default:default` already exists in k8s cluster.
#---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: gotty-account
 namespace: gotty-namespace

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

  # kubectl apply -f role-binding.yaml
  # kubectl delete -f role-binding.yaml