apiVersion: apps/v1
kind: Deployment
metadata:
  name: newpython
  labels:
    app: newpythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newpythonapp
  template:
    metadata:
      labels:
        app: newpythonapp
    spec:
      containers:
      - name: python-cont
        image: newpythonimg     #pythonimg
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5031
        volumeMounts:
        - name: mongo-storage
          mountPath: /data
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pv-claim
      