# apiVersion: v1
# kind: Service
# metadata:
#   name: python-service
#   labels:
#     app: python
# spec:
#   ports:
#   - protocol: TCP 
#     port: 5031
#     targetPort: 5031
#   type: ClusterIP
#   selector:
#     app: python
#     name : python-service
    

apiVersion: v1
kind: Service
metadata:
  name: newpython-node
  labels:
    app: newpythonapp
spec:
  selector:
    app: newpythonapp
  type: NodePort
  ports:
  - nodePort: 31022
    port: 5031
    targetPort: 5031